# Generated by Django 4.2.2 on 2023-06-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0016_remove_taxes_application_and_more'),
        ('user_profile', '0002_profile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='hr_system.employee', verbose_name='employee profile'),
        ),
    ]
