# Generated by Django 4.2.2 on 2023-06-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0023_manager_user'),
        ('user_profile', '0006_alter_managerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='hr_system.manager', verbose_name='manager profile'),
        ),
    ]
