# Generated by Django 4.2.2 on 2023-06-15 10:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='content',
            field=tinymce.models.HTMLField(choices=[(0, 'Vacation form'), (1, 'Termination form')]),
        ),
    ]
