# Generated by Django 4.2.2 on 2023-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0003_alter_application_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='content',
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.CharField(choices=[(0, 'Vacation form'), (1, 'Termination form')], db_index=True, default=0, max_length=50, verbose_name='template'),
        ),
    ]
