# Generated by Django 4.2.2 on 2023-06-15 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0005_application_content_alter_application_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'New'), (1, 'Approved'), (2, 'Declined')], db_index=True, max_length=50, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date(2023, 6, 15), verbose_name='hire date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Terminated')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='term_date',
            field=models.DateField(default=datetime.date(2023, 6, 15), verbose_name='termination date'),
        ),
        migrations.AddField(
            model_name='manager',
            name='hire_date',
            field=models.DateField(default=datetime.date(2023, 6, 15), verbose_name='hire date'),
        ),
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Terminated')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='manager',
            name='term_date',
            field=models.DateField(default=datetime.date(2023, 6, 15), verbose_name='termination date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='template',
            field=models.CharField(choices=[(0, 'Vacation form'), (1, 'Parent day-off form'), (2, 'Termination form'), (3, 'Taxes form')], db_index=True, max_length=50, verbose_name='template'),
        ),
    ]
