# Generated by Django 4.2.2 on 2023-06-16 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0008_alter_employee_hire_date_alter_employee_term_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
    ]
