# Generated by Django 4.2.2 on 2023-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0009_alter_application_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='term_date',
            field=models.DateField(verbose_name='termination date'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='term_date',
            field=models.DateField(verbose_name='termination date'),
        ),
    ]
