# Generated by Django 4.2.2 on 2023-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0010_alter_employee_term_date_alter_manager_term_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='termination date'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='term_date',
            field=models.DateField(blank=True, null=True, verbose_name='termination date'),
        ),
    ]
