# Generated by Django 4.2.2 on 2023-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0011_alter_employee_term_date_alter_manager_term_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Approved'), (2, 'Declined')], db_index=True, default=0, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='template',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Vacation form'), (1, 'Parent day-off form'), (2, 'Termination form'), (3, 'Taxes form')], db_index=True, default=0, verbose_name='template'),
        ),
    ]
