# Generated by Django 4.2.2 on 2023-06-16 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0012_alter_application_status_alter_application_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='content',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='template',
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, db_index=True, max_length=5000, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Approved'), (2, 'Declined')], db_index=True, default=0, null=True, verbose_name='status')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='hr_system.application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'application_instance',
                'verbose_name_plural': 'application_instances',
            },
        ),
    ]
