# Generated by Django 4.2.2 on 2023-06-19 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0014_parentdayoff_taxes_termination_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdayoff',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_system.application', verbose_name='application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxes',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_system.application', verbose_name='application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termination',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_system.application', verbose_name='application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_system.application', verbose_name='application'),
            preserve_default=False,
        ),
    ]
