# Generated by Django 4.2.2 on 2023-06-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0015_parentdayoff_application_taxes_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxes',
            name='application',
        ),
        migrations.RemoveField(
            model_name='termination',
            name='application',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='application',
        ),
        migrations.DeleteModel(
            name='ParentDayOff',
        ),
        migrations.DeleteModel(
            name='Taxes',
        ),
        migrations.DeleteModel(
            name='Termination',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
