# Generated by Django 4.2.2 on 2023-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0020_alter_applicationinstance_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationinstance',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'New'), (1, 'Approved'), (2, 'Declined')], db_index=True, default=0, null=True, verbose_name='status'),
        ),
    ]
