# Generated by Django 4.2.2 on 2023-06-21 16:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0021_alter_applicationinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=tinymce.models.HTMLField(blank=True, db_index=True, max_length=5000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='content'),
        ),
    ]
