# Generated by Django 4.2.2 on 2023-06-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0026_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='comment',
            field=models.TextField(blank=True, db_index=True, max_length=500, null=True, verbose_name='comment'),
        ),
    ]
